/**
 * \file CommandSerializer.hpp
 * \author Auto-coded
 * \brief Command Serializer header file 
 * This is generated by running the testcmd.sh script.
 *
 *
 * \copyright
 * Copyright 2009-2015, by the California Institute of Technology.
 * ALL RIGHTS RESERVED.  United States Government Sponsorship
 * acknowledged. Any commercial use must be negotiated with the Office
 * of Technology Transfer at the California Institute of Technology.
 * <br /><br />
 * This software may be subject to U.S. export control laws and
 * regulations.  By accepting this document, the user agrees to comply
 * with all U.S. export laws and regulations.  User has the
 * responsibility to obtain export licenses, or other export authority
 * as may be required before exporting such information to foreign
 * countries or providing access to foreign persons.
 */


#ifndef _COMMAND_SERIALIZER_HPP
#define _COMMAND_SERIALIZER_HPP

#include "Fw/Com/ComBuffer.hpp"
#include "Fw/Types/BasicTypes.hpp"
#include "Fw/Types/Serializable.hpp"


namespace Svc {

  namespace CommandSerializer {
  

    //! Serialize a CMD_NO_OP command
    //! return The serialization status
    Fw::SerializeStatus CMD_NO_OP (   
        Fw::ComBuffer& comBuffer //!< The result
    );
    

    //! Serialize a CMD_CLEAR_TRACKING command
    //! return The serialization status
    Fw::SerializeStatus CMD_CLEAR_TRACKING (   
        Fw::ComBuffer& comBuffer //!< The result
    );
    

    //! Serialize a CMD_TEST_CMD_1 command
    //! return The serialization status
    Fw::SerializeStatus CMD_TEST_CMD_1 (   
        I32 arg1,
        F32 arg2,
        U8 arg3,
        Fw::ComBuffer& comBuffer //!< The result
    );
    

  }

}

#endif

