/**
 * \file CommandOpcodes.hpp
 * \author Auto-coded
 * \brief Enumeration list containing command opcodes
 * This is generated by running the testcmd.sh script.
 *
 *
 * \copyright
 * Copyright 2009-2015, by the California Institute of Technology.
 * ALL RIGHTS RESERVED.  United States Government Sponsorship
 * acknowledged. Any commercial use must be negotiated with the Office
 * of Technology Transfer at the California Institute of Technology.
 * <br /><br />
 * This software may be subject to U.S. export control laws and
 * regulations.  By accepting this document, the user agrees to comply
 * with all U.S. export laws and regulations.  User has the
 * responsibility to obtain export licenses, or other export authority
 * as may be required before exporting such information to foreign
 * countries or providing access to foreign persons.
 */

#ifndef __COMMAND_OPCODES_HPP_
#define __COMMAND_OPCODES_HPP_

namespace Svc {

  namespace OPCODES {
  
  enum Opcodes {
    CMD_CLEAR_TRACKING = 0x503,
    CMD_TEST_CMD_1 = 0x502,
    CMD_NO_OP = 0x500,
  };
  
  }

}

#endif

