BACK-END = fprime
NAMESPACE = Svc
MODEL = FPManagerSm

autocode:
	@printf "**** Running the state-machine autocoder ****\n"
	../../STARS/autocoder/Stars.py $(BACK-END) -namespace $(NAMESPACE) -noImpl $(MODEL).plantuml
